version: 2
updates:
  # Update for GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"              # Directory for GitHub Actions workflows
    schedule:
      interval: "daily"        # Check for updates daily (previously mentioned as weekly)
      time: "08:00"            # Run every day at 08:00 UTC, day specification removed as it's redundant
    labels:
      - "github-actions"
    assignees:
      - "Githubguy132010"
