name: Cleanup Old Releases

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
