name: Delete Old Releases

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      keep_latest:
        description: 'Number of latest releases to keep'
        required: true
        default: '1'

jobs:
  delete-old-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.keep_latest || '1' }}
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}