name: Check to make sure Dockerfile works

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # Run the workflow every day at midnight
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest  # Use a standard runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Run Docker container
        run:
          docker build -t arch-iso-builder . && \
          docker run --rm --privileged -v "$(pwd)":/workdir arch-iso-builder bash -c "mkarchiso -v -w workdir/ -o out/ ."
