name: Generate Release Notes

on:
  release:
    types: [created]

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Release Notes
        id: generate_release_notes
        uses: release-drafter/release-drafter@v5
        env:
          FAIL_COMMENT_NAME: "Generate Release Notes"
          FAIL_COMMENT_MESSAGE: "An error occurred during the release notes generation process."
          FAIL_COMMENT_CONTEXT: "GitHub Actions Workflow"
          FAIL_COMMENT_DETAILS: "Check the logs for more details."
        with:
          config-name: release-drafter.yml

      - name: Create Release Notes
        run: |
          echo "Release notes generated successfully"
