name: Update Packages

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Docker
        run: |
          docker run --name arch-container -d archlinux:latest sleep infinity

      - name: Check for Package Updates
        id: check-updates
        run: |
          # Create temporary files
          touch new-packages.txt current-packages.txt updates.txt
          
          # Get current packages
          cat packages.x86_64 | grep -v '^#' | grep -v '^$' > current-packages.txt
          
          # Check each package for updates
          docker exec arch-container bash -c "
            pacman -Sy
            while read -r pkg; do
              if pacman -Si \$pkg >/dev/null 2>&1; then
                echo \$pkg >> /tmp/new-packages.txt
              fi
            done < /workdir/current-packages.txt
          "
          
          # Compare versions and create update list
          docker exec arch-container bash -c "
            while read -r pkg; do
              current_ver=\$(pacman -Si \$pkg | grep Version | head -n1 | awk '{print \$3}')
              echo \"\$pkg \$current_ver\" >> /tmp/updates.txt
            done < /tmp/new-packages.txt
          "
          
          # Copy files back
          docker cp arch-container:/tmp/updates.txt .
          
          # Set output
          if [ -s updates.txt ]; then
            echo "updates_available=true" >> $GITHUB_OUTPUT
          else
            echo "updates_available=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-updates.outputs.updates_available == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update package versions"
          title: "📦 Automatic Package Updates"
          body: |
            🔄 Automatic package update
            
            The following packages have been updated to their latest version:
            ```
            $(cat updates.txt)
            ```
            
            This PR was automatically generated by the update-packages workflow.
          branch: package-updates
          base: dev
          labels: |
            automated
            dependencies
          draft: false

      - name: Clean Up
        if: always()
        run: |
          docker stop arch-container || true
          docker rm arch-container || true
          rm -f updates.txt new-packages.txt current-packages.txt